import {useCallback,useEffect,useMemo,useState} from 'react'
import {ArrowDownLeft,ArrowRight,ArrowUpRight,Check,Clock3,Coins,Info,RefreshCw,ShieldCheck,Wallet,WifiOff,X} from 'lucide-react'
import {api} from './api'

const money = value => new Intl.NumberFormat('en-PK',{style:'currency',currency:'PKR',maximumFractionDigits:2}).format(Number(value||0)).replace('PKR','Rs')
const grams = value => `${Number(value||0).toLocaleString('en-PK',{maximumFractionDigits:6})} g`
const when = value => value ? new Intl.DateTimeFormat('en-PK',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)) : '—'

function App(){
  const [portfolio,setPortfolio]=useState(null), [price,setPrice]=useState(null), [trades,setTrades]=useState([])
  const [side,setSide]=useState('buy'), [unit,setUnit]=useState('pkr'), [amount,setAmount]=useState('')
  const [quote,setQuote]=useState(null), [receipt,setReceipt]=useState(null), [remaining,setRemaining]=useState(0)
  const [busy,setBusy]=useState(false), [error,setError]=useState(''), [loading,setLoading]=useState(true)
  const load=useCallback(async()=>{setError('');const [p,m,t]=await Promise.allSettled([api.portfolio(),api.price(),api.trades()]);if(p.status==='fulfilled')setPortfolio(p.value);if(m.status==='fulfilled')setPrice(m.value);else{setPrice(null);setError(m.reason.message)}if(t.status==='fulfilled')setTrades(t.value);setLoading(false)},[])
  useEffect(()=>{load()},[load])
  useEffect(()=>{if(!quote)return; const tick=()=>setRemaining(Math.max(0,Math.ceil((new Date(quote.expires_at)-Date.now())/1000)));tick();const id=setInterval(tick,250);return()=>clearInterval(id)},[quote])
  const effective=useMemo(()=>price?(side==='buy'?price.customer_buy_pkr_per_gram:price.customer_sell_pkr_per_gram):0,[price,side])
  const estimate=Number(amount)>0?(unit==='pkr'?Number(amount)/effective:Number(amount)*effective):0
  const changeSide=(next)=>{setSide(next);setQuote(null);setReceipt(null);setError('')}
  const getQuote=async()=>{if(!Number(amount)||Number(amount)<=0){setError('Enter an amount greater than zero.');return}setBusy(true);setError('');try{const q=await api.quote({side,amount:Number(amount),amount_unit:unit});setQuote(q);setRemaining(q.seconds_remaining);setReceipt(null)}catch(e){setError(e.message)}finally{setBusy(false)}}
  const confirm=async()=>{setBusy(true);setError('');try{const trade=await api.confirm(quote.id);setReceipt(trade);setQuote(null);setAmount('');await load()}catch(e){setError(e.message);if(e.reason==='quote_expired')setRemaining(0)}finally{setBusy(false)}}
  return <div className="app">
    <header><a className="brand" href="#"><span className="brandmark">A</span><span>ASASA<small>GOLD, MADE CLEAR</small></span></a><div className="secure"><ShieldCheck size={17}/> Secure demo</div></header>
    <main>
      <section className="intro"><div><span className="eyebrow">24K GOLD · PKR PER GRAM</span><h1>Your gold. Your terms.</h1><p>Buy and sell with a locked price, clear fees, and no surprises.</p></div>
        <div className={`market ${price?'':'offline'}`}>{price?<><div><span className="live"><i/> LIVE MARKET</span><strong>{money(price.pkr_per_gram)}</strong><small>per gram · 24K</small></div><div className="fresh"><span>Source: <b>{price.source}</b></span><span>Updated {when(price.observed_at)}</span></div></>:<><WifiOff/><div><strong>Pricing paused</strong><small>We’ll resume trading when a trusted source responds.</small></div></>}</div>
      </section>
      {error&&<div className="alert"><Info size={19}/><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss"><X size={18}/></button></div>}
      <section className="balances"><div><span><Wallet/> Available cash</span><strong>{loading?'Loading…':money(portfolio?.cash_pkr)}</strong><small>Pakistani rupees</small></div><div><span><Coins/> Your gold</span><strong>{loading?'Loading…':grams(portfolio?.gold_grams)}</strong><small>24 karat holdings</small></div><div><span><ShieldCheck/> Platform inventory</span><strong>{loading?'Loading…':grams(portfolio?.platform_gold_grams)}</strong><small>Available to buy</small></div></section>
      <section className="trade-layout"><div className="trade-card">
        <div className="tabs"><button className={side==='buy'?'active':''} onClick={()=>changeSide('buy')}><ArrowDownLeft/> Buy gold</button><button className={side==='sell'?'active':''} onClick={()=>changeSide('sell')}><ArrowUpRight/> Sell gold</button></div>
        {!quote&&!receipt&&<div className="entry"><div className="section-title"><span>1</span><div><h2>Choose your amount</h2><p>Enter either rupees or gold weight.</p></div></div><div className="unit-toggle"><button className={unit==='pkr'?'active':''} onClick={()=>setUnit('pkr')}>Pakistani rupees</button><button className={unit==='gold'?'active':''} onClick={()=>setUnit('gold')}>Gold grams</button></div><label>{unit==='pkr'?'Amount in PKR':'Weight in grams'}<div className="amount"><span>{unit==='pkr'?'Rs':'g'}</span><input autoFocus inputMode="decimal" placeholder={unit==='pkr'?'100,000':'2.000'} value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,''))}/></div></label>{Number(amount)>0&&<div className="estimate"><span>You’ll {side==='buy'?'receive approximately':'receive'}</span><b>{unit==='pkr'?grams(estimate):money(estimate)}</b></div>}<div className="rate-row"><span>Your {side} rate</span><b>{money(effective)} / g</b><small>{side==='buy'?`10% markup; ${money(price?.buy_guardrail_pkr)} minimum guardrail`:'90% of market reference'}</small></div><button className="primary" disabled={busy||!price} onClick={getQuote}>{busy?'Locking price…':<>Review trade <ArrowRight/></>}</button></div>}
        {quote&&<div className="review"><div className="section-title"><span>2</span><div><h2>Review your trade</h2><p>This exact price is reserved for you.</p></div></div><div className={`countdown ${remaining<=15?'urgent':''}`}><Clock3/><div><span>Quote expires in</span><strong>{remaining}s</strong></div><div className="bar"><i style={{width:`${remaining/75*100}%`}}/></div></div><dl><div><dt>Action</dt><dd>{side==='buy'?'Buy':'Sell'} 24K gold</dd></div><div><dt>Gold amount</dt><dd>{grams(quote.gold_grams)}</dd></div><div><dt>Locked rate</dt><dd>{money(quote.unit_price_pkr)} / g</dd></div><div className="total"><dt>{side==='buy'?'You pay':'You receive'}</dt><dd>{money(quote.total_pkr)}</dd></div></dl><div className="source-note"><ShieldCheck/><span>Locked from <b>{quote.price_source}</b> · Market observed {when(quote.price_observed_at)}</span></div>{remaining>0?<button className="primary" disabled={busy} onClick={confirm}>{busy?'Settling trade…':<>Confirm {side} <Check/></>}</button>:<button className="primary" onClick={getQuote}><RefreshCw/> Get a fresh quote</button>}<button className="text-button" onClick={()=>setQuote(null)}>Change amount</button></div>}
        {receipt&&<div className="receipt"><div className="success"><Check/></div><span className="eyebrow">TRADE COMPLETE</span><h2>{side==='buy'?'Gold purchased':'Gold sold'} successfully</h2><p>Your balances were updated together. Keep this receipt for your records.</p><dl><div><dt>Receipt ID</dt><dd>{receipt.id.slice(0,8).toUpperCase()}</dd></div><div><dt>Gold</dt><dd>{grams(receipt.gold_grams)}</dd></div><div><dt>Rate</dt><dd>{money(receipt.unit_price_pkr)} / g</dd></div><div className="total"><dt>{side==='buy'?'Paid':'Received'}</dt><dd>{money(receipt.total_pkr)}</dd></div><div><dt>Completed</dt><dd>{when(receipt.created_at)}</dd></div></dl><button className="primary" onClick={()=>setReceipt(null)}>Make another trade <ArrowRight/></button></div>}
      </div><aside><h3>How pricing works</h3><div className="explain"><span>Market</span><b>{money(price?.pkr_per_gram)}</b></div><div className="formula"><div><ArrowDownLeft/><span>When you buy<small>max(market × 1.10, guardrail)</small></span></div><b>{money(price?.customer_buy_pkr_per_gram)}</b></div><div className="formula"><div><ArrowUpRight/><span>When you sell<small>market × 0.90</small></span></div><b>{money(price?.customer_sell_pkr_per_gram)}</b></div><p><Info/> The difference covers price movement and operating costs. You always see the final rate before confirming.</p></aside></section>
      <section className="activity"><div><span className="eyebrow">YOUR ACTIVITY</span><h2>Recent trades</h2></div>{trades.length?<div className="trade-list">{trades.map(t=><article key={t.id}><span className={`trade-icon ${t.side}`} >{t.side==='buy'?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div><b>{t.side==='buy'?'Bought':'Sold'} {grams(t.gold_grams)}</b><small>{when(t.created_at)} · {t.id.slice(0,8).toUpperCase()}</small></div><strong>{t.side==='buy'?'-':'+'}{money(t.total_pkr)}</strong></article>)}</div>:<div className="empty">Your completed trades will appear here.</div>}</section>
    </main><footer><span>ASASA · DEMO TRADING EXPERIENCE</span><span>All balances are simulated. No real money moves.</span></footer>
  </div>
}
export default App
